import Head from "next/head";
import Products from "../components/home-products";
import Layout from "../components/layout/layout";
import { caseToUpper } from "../components/myFunctions";
import Animate from "../components/animation";
import PageTransition from "../components/pageTransition";
import { useEffect, useState } from "react";

function Home() {
  const [products, setProducts] = useState();

  async function getProducts() {
    const res = await fetch("/json/products.json");
    const items = await res.json();

    setProducts(items.products);
  }

  useEffect(() => {
    getProducts();
  }, []);

  return (
    <PageTransition>
      <Animate>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Animate className="container-fluid">
          <div className="row">
            <Animate variant={"fadeIn"} className="col-6 p-5">
              <div className="py-5">
                <p className="display-5">
                  The <b className="text-orange-500">Import / Export Traders</b>{" "}
                  You Can <b className="text-orange-500">Trust</b>
                </p>
                <br />
                <p className="display-7">
                  {caseToUpper(
                    "A Company that has been importing / exporting goods with many years of excellent service."
                  )}
                </p>
              </div>
            </Animate>
            <Animate variant={"fadeIn"} className="col-6 p-4">
              <div className="cargo-ship-img">
                <img src="/cargo_ship_blob.png" className="img-fluid" />
              </div>
            </Animate>
          </div>
        </Animate>

        <div className="container-fluid p-5" style={{ background: "#ffb871" }}>
          <p className="h1 pb-5 text-center text-white underline">
            Our Products
          </p>
          {products && <Products productItems={products} />}
        </div>

        <Animate className="container-fluid p-5">
          <p className="h1 pb-5 text-center text-orange-500 underline">
            About Us
          </p>
          <div className="row">
            <Animate variant={"fadeIn"} className="col-6 display-6">
              Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam
              nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam
              erat volutpat. Ut wisi enim ad minim veniam
            </Animate>
            <Animate variant={"fadeIn"} className="col-6">
              <img src="/cargo_ship_2.jpg" className="img-fluid rounded" />
            </Animate>
          </div>
        </Animate>
      </Animate>
    </PageTransition>
  );
}

// Home.displayName = "Home";
// export default PageTransition(Home);
export default Home;

// export default <PageTransition OriginalComponent={Home} />;
